version: '3'

services:
  nuxt:
    container_name: nuxt
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/workspace
    working_dir: /workspace
    tty: true
    environment:
    - CHOKIDAR_USEPOLLING=true
    command: yarn run dev